/**
 * Micro-app entry file (template file - managed by the system, do not modify manually)
 * 微应用入口文件（模板文件 - 由系统管理，勿手动修改）
 *
 * This file is auto-generated by the Sun-Panel micro-app template and will be overwritten on upgrade.
 * 本文件由 Sun-Panel 微应用模板自动生成，升级时会被覆盖。
 * - Add new locale: create a .js or .json file in the locales/ directory
 *   新增语言：在 locales/ 目录下添加对应的 .js 或 .json 文件即可
 * - Register new component: add it in config/components.config.js
 *   新增组件：在 config/components.config.js 中注册
 * - App configuration: modify config/app.config.js
 *   应用配置：在 config/app.config.js 中修改
 */
import componentsConfig from '../config/components.config.js';
import appConfig from '../config/app.config.js';
import { VERSION as SP_API_VERSION, initSDK } from '@sun-panel/micro-app';

// =============================================
// Auto-import all translation files from the locales/ directory
// 使用 import.meta.glob 自动发现 locales/ 目录下的所有翻译文件
// =============================================
/** @type {Record<string, any>} */
const localeModules = import.meta.glob('../locales/*.{js,json}', { eager: true });
/** @type {Record<string, any>} */
const translations = {};
for (const [filePath, mod] of Object.entries(localeModules)) {
  const match = filePath.match(/\/([^/]+)\.(?:js|json)$/);
  if (match) {
    translations[match[1]] = (mod && mod.default) || mod;
  }
}

// =============================================
// Initialize SDK (template code, do not modify)
// 初始化 SDK（模板代码，勿手动修改）
// =============================================
initSDK({
  translations,
  defaultLocale: appConfig.defaultLocale || 'en-US',
  dev: import.meta.env.DEV,
});

// =============================================
// Micro-app package definition (system-managed, do not modify)
// 微应用包定义（系统管理区域，勿手动修改以下代码）
// =============================================
// 环境区分（由 package.json 中的 VITE_MICRO_MODE 环境变量控制）：
//   npm run dev（在线运行）          → -dev 后缀
//   pack:dev / pack:test（打包测试） → -test 后缀
//   npm run pack（正式打包）         → 无后缀
const runMode = import.meta.env.VITE_MICRO_MODE; // 'dev' | 'test' | undefined(生产)
const isDevMode = runMode === 'dev' || runMode === 'test';
const getMicroAppId = (config, mode) => {
  if (mode === 'dev') return `${config.microAppId}-dev`;
  if (mode === 'test') return `${config.microAppId}-test`;
  return config.microAppId;
};

const microAppPackage = {
  appConfig: {
    ...appConfig,
    apiVersion: SP_API_VERSION,
    microAppId: getMicroAppId(appConfig, runMode),
    dev: isDevMode,
  },
  components: componentsConfig,
};

export default microAppPackage;